package com.ceslab.firemesh.meshmodule.model

/**
 * Created by Viet Hua on 11/30/2020.
 */

enum class ConfigurationTask {
    CONFIG_BIND_NODE_TO_GROUP,
    CONFIG_UNBIND_NODE_FROM_GROUP,
    CONFIG_CONTROL_NODE_SUCCEED,
    CONFIG_BIND_MODEL_TO_GROUP,
    CONFIG_UNBIND_MODEL_FROM_GROUP,
    CONFIG_CONTROL_MODEL_SUCCEED,
    CONFIG_PUBLICATION_SETTING,
    CONFIG_PUBLICATION_CLEARING,
    CONFIG_CONTROL_PUBLICATION_SUCCEED,
    CONFIG_SUBSCRIPTION_ADDING,
    CONFIG_SUBSCRIPTION_REMOVING,
    CONFIG_CONTROL_SUBSCRIPTION_SUCCEED,
    CONFIG_PROXY_ENABLING,
    CONFIG_PROXY_DISABLING,
    CONFIG_PROXY_CHECKING,
    CONFIG_FRIEND_ENABLING,
    CONFIG_FRIEND_DISABLING,
    CONFIG_FRIEND_CHECKING,
    CONFIG_RETRANSMISSION_ENABLING,
    CONFIG_RETRANSMISSION_DISABLING,
    CONFIG_RETRANSMISSION_CHECKING,
    CONFIG_RELAY_ENABLING,
    CONFIG_RELAY_DISABLING,
    CONFIG_RELAY_CHECKING
}