package com.ceslab.firemesh.meshmodule.model

/**
 * Created by Viet Hua on 11/30/2020.
 */

enum class ConfigurationStatus {
    BIND_NODE_TO_GROUP,
    UNBIND_NODE_FROM_GROUP,
    BIND_MODEL_TO_GROUP,
    UNBIND_MODEL_FROM_GROUP,
    SET_PUBLICATION_SETTING,
    CLEAR_PUBLICATION_SETTING,
    ADD_SUBSCRIPTION_SETTING,
    REMOVE_SUBSCRIPTION_SETTING,
    NODE_CONFIG_FINISHED

}